Authentication project implementation
andresporras3423/members-only pull request #2
Opened 2020-03-17 16:55 UTC by Salvador-ON

- It has two model: User, Post
- The User has 3 attributes:name, email, and password with the respective validation, remeber token.
- The Post has 2 attributes:comment, user_id
- In the front-end we can create new users and create new posts, when the user isn't logged in. The autor name is hidden

2020-03-17 23:07 UTC, maelfosso requested changes
# Changes required  :red_circle: 

Hello, thank you the job done! Really simple!!
However, there are changes to do

1. After login, I check the database
```ruby
2.6.3 :001 > User.find_by(:email => "alice@bar.com")
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = ? LIMIT ?  [["email", "alice@bar.com"], ["LIMIT", 1]]
 => #<User id: 12, name: "Alice", email: "alice@bar.com", password_digest: "$2a$12$N2j/9gnAZ3a9QC/tpy/eeu.22MWOiq7FK/DpgKynJjD...", member_status: nil, created_at: "2020-03-17 22:54:05", updated_at: "2020-03-17 22:54:05", remember_token: nil> 
2.6.3 :002 > 
```
You could notice that the `remember_token` is nil. It should have the token as indicated [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/sign_in_method_requirement.png)

2. Forgot about **using SESSION**. 
> The `remember_me` token the project describes consists of storing a hash in a cookie and using it to determine in a user is logged in. Do not confuse it with the Remember me [ ] checkbox that many websites show. That is a more complex solution, which is not required here

3. When **log_out**, you should delete the `remember_token` from the cookies and set it to `nil` into the user.

4. At the end of the sign in, you should set the current user variable ie `@current_user`.

5. Read the comments below, please.

Kindly make the suggested changes and submit a new code review request.
Thanks

Mael FOSSO

2020-03-17 23:07 UTC, maelfosso commented on app/helpers/sessions_helper.rb
> +  end
Not needed

2020-03-17 23:07 UTC, maelfosso commented on app/helpers/sessions_helper.rb
> +  end
You should set the `@current_user` to the one who signed

2020-03-17 23:07 UTC, maelfosso commented on app/helpers/sessions_helper.rb
> +  end
Too long!!!
Re-read this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/current_user_requirement.png)

2020-03-17 23:07 UTC, maelfosso commented on app/helpers/sessions_helper.rb
> +  end
It's not `user == current_user`
You should defined the `@current_user` here

2020-03-18 16:07 UTC, andresporras3423 commented
Thanks for the feedback

* not using session anymore
* login with cookies
* cookies=nil when log out
* using current_user= method to update current user
* deleted unnecessary methods

2020-03-18 18:21 UTC, samgaco reviewed
Hi @andresporras3423 and @Salvador-ON :high_brightness: 

You have implemented the changes, the project is approved :+1: 

-----------------

* ###### STATUS OF THE PROJECT: APPROVED :heavy_check_mark:

2020-03-18 18:21 UTC, samgaco commented on app/models/user.rb
> +    self.remember_token == remember_token
:+1:

2020-03-18 19:16 UTC, andresporras3423 commented
Thank you

2020-03-18 19:16 UTC, merged